---

- name: Add mongodb-org key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

- name: Add mongodb apt sources list deb
  apt_repository:
    repo: 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse'
    state: present

- name: Install mongodb-org
  action: apt pkg=mongodb-org state=installed update-cache=yes
